### ISSUE TITLE
Ability to refresh files changed remotely

### ISSUE THREAD

**Issue by japhib** [sveale/remote-edit#135]
Hello,

Is there a way to "refresh" the files and see if they have been changed on the server? That is, to re-download them? I've been using your package and find it very useful and convenient for all SSH editing of files. However, the package assumes that you're the only one editing it. This makes it so if you want to view a log file that is occasionally changing, just re-opening it through ctrl-cmd-O, I have to navigate to its location again in the file system and open it that way. When you re-open the file (after pressing control-command-O), is it possible it could just re-download it?

Thanks,
Japhib

**Comment by sveale** [comment]
Hi Japhib,

If I remember correctly, the functionality you describe existed in some form in previous versions of remote-edit. I removed it because I didn't want the hassle of syncing two files, but it should be quite straightforward to add an option that makes it so that the file is re-downloaded each time you open it through ctrl-cmd-O. 

I'm afraid I probably won't be able to look at it anytime soon, but would very much appreciate a pull request. Let me know if you'd be interested in implementing it, and I could point you in the right direction.

**Comment by Gnarlywhale** [comment]
I'd be happy to take a look at it if you point me in the right direction.

**Comment by sveale** [comment]
I think the easiest and best way to do this would be to modify the ``openFile`` method in ``files-view.coffee`` such that it first sees if the host already have a localfile with the url you're downloading. Look at ``atom.config.get`` for how to query settings.
