### ISSUE TITLE
Password input value is not hidden

### ISSUE THREAD

**Issue by valanz** [sveale/remote-edit#49]
When creating a new host, the value of the password input is readable. It should be hidden to avoid malicious behavior.

**Comment by sveale** [comment]
Related to issue #45 .

Since passwords/passphrase isn't encrypted on the backend, I haven't bothered with hiding them under input either. As far as I know there is no easy way to do this in Atom (https://discuss.atom.io/t/password-fields-when-using-editorview-subview/11061/3). It probably won't be addressed until #45 is resolved.

Thanks for the input :)
