### ISSUE TITLE
invoking remote edit from another package?

### ISSUE THREAD

**Issue by mark-hahn** [sveale/remote-edit#79]
I have a `command-toolbar` package that I use like favorites in a browser.  It stores atom commands, links to files, and web pages.  I'd like to extend the stored links to remote files using this package.  How hard would it be to ...
- Ask for the remote info for the focused file for me to save?
- Ask remote edit to bring up that file later with that info?

**Comment by sveale** [comment]
When editing remote files a _RemoteEditEditor_ is used instead of the default _TextEditor_. 
This class has two variables which can be used to accomplish what you want: __localFile__ and __host__.

The easiest way to save the info for the focused file would be to use these to variables to generate and store a string that could later be used to open said file. 
Look at [open-files-view.coffee](https://github.com/sveale/remote-edit/blob/03a079ba2ad9617873fffa452535f3d6c07f0c1d/lib/view/open-files-view.coffee#L59) on line 59. You can open the generated URI using atom.workspace.open.

Hope this helps. Let me know if there's anything I can do to help.

**Comment by mark-hahn** [comment]
Sounds great.  I was very surprised to see that remote pages reload when
atom reloads.  Nice package.
