### ISSUE TITLE
Feature request - Ability to book mark file and import all the files from a directory

### ISSUE THREAD

**Issue by xpl0iter** [sveale/remote-edit#80]
Hello,
I am sorry if this is not the right place. I have two feature requests.
1. Ability to bookmark a directory and/or a file
2. Ability to open all the files from a directory like it was a project folder.

**Comment by sveale** [comment]
Hi,

This is the right place :)

 1. This is already present in a way. Have a look at the "Show downloaded files" functionality. Unfortunately this only works for files. But you can create multiple instances of the same host using different directories, and label them accordingly. I don't think any bookmarking feature is strictly necessary because of these functions, but you're more than welcome to try and implement it yourself.
 2. This is related to issue #25 I believe. It's definitely something that would be very useful, but because of time constraints I haven't been able to implement it myself.
